### ISSUE TITLE
Errores de consola

### ISSUE THREAD

**Issue by Nidev-lab** [maxigiordani/ProyectoVeterinaria#4]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que no se encuentre errores en la consola.

## Resultado actual

• Al ingresar se visualizan errores en la consola. 

## Captura

![image](https://github.com/maxigiordani/ProyectoVeterinaria/assets/53904695/acae7112-0951-4abe-8956-47be97ece887)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas! Como estan? Si bien ahora lo errores por consola no se muestran, aun se sigue mostrando informacion que no debería de verse, por consola no se debería de ver ningún tipo de informacion.
![image](https://github.com/maxigiordani/ProyectoVeterinaria/assets/53904695/829ca7ec-9bff-417c-ad9a-f1a8f901a9e8)

**Comment by maxigiordani** [comment]
Buenas tardes! ya esta solucionado, ya no se muestra por consola ninguna información!
