### ISSUE TITLE
Añadir paciente (Admin)

### ISSUE THREAD

**Issue by Nidev-lab** [maxigiordani/ProyectoVeterinaria#6]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario admin.
3. Quise agregar nuevos pacientes.

## Resultado esperado

• Poder crear un nuevo paciente sin inconvenientes.

## Resultado actual

• Al darle al boton "añadir paciente" se produce un error que muestra por consola y no me permite crear el nuevo paciente.

## Captura

![image](https://github.com/maxigiordani/ProyectoVeterinaria/assets/53904695/1da65d85-7f7f-450b-bc0b-72a56e4ccb59)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas! Como están? Si bien ahora se puede añadir un nuevo paciente y no se muestra ningún error, lo que pasa ahora es que al crear un paciente nuevo se muestra toda la informacion por consola y eso no se deberia de ver.
![image](https://github.com/maxigiordani/ProyectoVeterinaria/assets/53904695/2c7fcda1-750c-45c3-86b0-721fca933a71)

**Comment by maxigiordani** [comment]
Buenas tardes! ya esta solucionado, ya no se muestra por consola ninguna información en esta pagina tampoco!
