### ISSUE TITLE
Turnos (Admin)

### ISSUE THREAD

**Issue by Nidev-lab** [maxigiordani/ProyectoVeterinaria#7]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario admin.
3. Quise agendar unos turnos.

## Resultado esperado

• Poder agendar turnos nuevos sin problemas.

## Resultado actual

• Al tratar de agregar un nuevo turno se produce un error que se muestra por consola y no me permite crear el nuevo turno.

## Captura

![image](https://github.com/maxigiordani/ProyectoVeterinaria/assets/53904695/920bb6e4-b794-4962-9920-c166f38ca88b)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas! Como estan? Si bien ahora puedo crear un nuevo turno sin problema aun queda informacion, por consola no se debería de ver ningún tipo de informacion.
![image](https://github.com/maxigiordani/ProyectoVeterinaria/assets/53904695/c963d419-f323-4619-9119-407797c9d673)

**Comment by maxigiordani** [comment]
en esta pagina también pudimos solucionar esta información que por consola que no debía mostrarse !
